export enum ClinicalState {
  SYSTEM_IDLE = "SYSTEM_IDLE",
  PATIENT_OPEN = "PATIENT_OPEN",
  SESSION_READY = "SESSION_READY",
  SESSION_ACTIVE = "SESSION_ACTIVE",
  SESSION_PAUSED = "SESSION_PAUSED",
  SESSION_ENDED = "SESSION_ENDED",
  CLINICAL_ERROR = "CLINICAL_ERROR"
}