/**
 * CLINICAL EVENTS — EXPLÍCITOS
 * UI apenas emite eventos, nunca decide
 */

export enum ClinicalEvent {
  OPEN_PATIENT = "OPEN_PATIENT",
  CLOSE_PATIENT = "CLOSE_PATIENT",

  PREPARE_SESSION = "PREPARE_SESSION",
  START_SESSION = "START_SESSION",
  PAUSE_SESSION = "PAUSE_SESSION",
  RESUME_SESSION = "RESUME_SESSION",
  END_SESSION = "END_SESSION",

  FAIL = "FAIL",
  RESET = "RESET"
}
